[package]
name = "games"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "debug_binpack"
path = "src/debug_binpack.rs"

[dependencies]
engine = {path = "../engine"}
features = {path = "../features"}
common = {path = "../common"}
cozy-chess = "0.3.4"
rand = "0.8.5"
rayon = "1.5.3"
bytemuck = "1.12.1"
itertools = "0.10.3"
bincode = "1.3.3"
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0"
clap = {version = "4.5", features = ["derive"]}
sfbinpack = "0.6.5"
anyhow = "1.0.104"
tempfile = "3.27.0"
indicatif = "0.18.6"
plotly = "0.8.4"

[profile.release]
debug = true

[build]
rustflags = ["-C", "target-cpu=native"]
